"""empty message

Revision ID: 47e986cfd8f0
Revises: 7cc803071cfa
Create Date: 2020-06-11 21:14:49.818471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47e986cfd8f0"
down_revision = "7cc803071cfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rel_user_role",
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("role_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
    )
    op.create_index(
        op.f("ix_rel_user_role_role_id"),
        "rel_user_role",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rel_user_role_user_id"),
        "rel_user_role",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rel_user_role_user_id"), table_name="rel_user_role")
    op.drop_index(op.f("ix_rel_user_role_role_id"), table_name="rel_user_role")
    op.drop_table("rel_user_role")
    # ### end Alembic commands ###
