"""empty message

Revision ID: 7a23cf8e647a
Revises: 47e986cfd8f0
Create Date: 2020-06-13 08:51:21.871516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a23cf8e647a"
down_revision = "47e986cfd8f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rel_role_permission",
        sa.Column("role_id", sa.String(), nullable=True),
        sa.Column("permission_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["permission_id"], ["permission.id"],),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"],),
    )
    op.create_index(
        op.f("ix_rel_role_permission_permission_id"),
        "rel_role_permission",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rel_role_permission_role_id"),
        "rel_role_permission",
        ["role_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rel_role_permission_role_id"),
        table_name="rel_role_permission",
    )
    op.drop_index(
        op.f("ix_rel_role_permission_permission_id"),
        table_name="rel_role_permission",
    )
    op.drop_table("rel_role_permission")
    # ### end Alembic commands ###
